/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-west-2",
  aws_cognito_identity_pool_id: "us-west-2:a2cb5a9d-d728-4c5c-a96e-b2973d14c5e0",
  aws_cognito_region: "us-west-2",
  aws_user_pools_id: "us-west-2_jseVZL1mh",
  aws_user_pools_web_client_id: "36nivl36qlp8fbnkpd2jv52fu",
  oauth: {},
  aws_mobile_analytics_app_id: "c4a87de1250246e491ab2d90d2db162f",
  aws_mobile_analytics_app_region: "us-west-2",
  aws_content_delivery_bucket: "thinkquicreactfronte-20210211155341-hostingbucket-dev",
  aws_content_delivery_bucket_region: "us-west-2",
  aws_content_delivery_url: "https://d27nvasfpedpzh.cloudfront.net",
  aws_appsync_graphqlEndpoint: "https://7zmvw77ngrhorm2rplc5j7tzta.appsync-api.us-west-2.amazonaws.com/graphql",
  aws_appsync_region: "us-west-2",
  aws_appsync_authenticationType: "AMAZON_COGNITO_USER_POOLS",
};

export default awsmobile;
